travis:
  secure:
    BINSTAR_TOKEN: RxJFXMo9Xbb+/pYFUgd2gSeI+G5AaaJrzTRIZoPnk4fYCGfRy9VYkhGTGNG+6N/IqSfN/WVF3CmlDgPU8Iy0maxFK99tl8qePFv7d3T4nr6U3vx1pH3XZ8pN2+MOczCE4ZsQIFPA2hO5WAruxOLXAsHEsQrEpiTs5JooW9+47KncVOxKLPanZXUquRDkRysLE28kxIP98xc7VEWnNvwnL0t39sPAcPQcwmYMbcePCj7wgtgRPQs2wJt5tYzNZyiTG+b1x6MP5fCY3wE4BtJZgNJQXHLcXY5+O0mBDzds0iNlHvCByjJTUs6HN74hCsNXMiRQrRUN8duFvnlSHmLPCVo0Xlo9jRvm3Cg+mAGwjffIInK4iyWXVGnLzsMvxYrZdO+DzWP9xUMNCXweYGhltGp77RuDMGC7wJu/eL0HZCUVGqv3s7vytJW0mVvip4g6JXTZUDTAMmfa7HLUT9MvrAc/aw9Ye0XNM6waRsOqzBlTLrSryNKrafcZ04ZcYA1K5TNkKGRRBozJExVZ9YtNMcg4orqEQ9binV0FwPVaq/nXmaMMM2dpLSYz4VlatTw8lOHAvmk1nikDRdiqMiEy/yYeSUrGDqFik+/YdRwfX6gf84TMCaf308lmRtpZW5UUkxqvlwULbGec8MaVXAEmwDT1/ZYrwC+M3iuJGi6FDLs=
conda_forge_output_validation: true
bot:
  automerge: true
